# Generated by Django 5.2.4 on 2026-05-15 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('event_date', models.DateField(verbose_name='일정 날짜')),
                ('event_type', models.CharField(choices=[('comeback', '컴백'), ('concert', '콘서트'), ('fansign', '팬사인회'), ('other', '기타')], default='other', max_length=20, verbose_name='일정 유형')),
                ('artist', models.CharField(blank=True, max_length=100, verbose_name='아티스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정 목록',
                'ordering': ['event_date'],
            },
        ),
    ]
