# Generated by Django 5.2.4 on 2026-05-22 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='질문 내용')),
                ('question_type', models.CharField(choices=[('TEXT', '주관식 단답'), ('TEXTAREA', '주관식 장문'), ('CHOICE', '객관식 단일'), ('MULTIPLE', '객관식 복수'), ('SCALE', '척도 1-5')], max_length=20, verbose_name='질문 유형')),
                ('required', models.BooleanField(default=True, verbose_name='필수 여부')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='선택지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='응답자')),
            ],
            options={
                'verbose_name': '응답',
                'verbose_name_plural': '응답 목록',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='답변')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question', verbose_name='질문')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response', verbose_name='응답')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변 목록',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 응답')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='설문'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='설문'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('survey', 'respondent')},
        ),
    ]
